export const GET_COMPANY = "GET_COMPANY"
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS"
export const GET_COMPANY_FAIL = "GET_COMPANY_FAIL" 

export const GET_COMPANY_ID = "GET_COMPANY_ID"
export const GET_COMPANY_ID_SUCCESS = "GET_COMPANY_ID_SUCCESS"
export const GET_COMPANY_ID_FAIL = "GET_COMPANY_ID_FAIL"

export const CREATE_COMPANY = "CREATE_COMPANY"
export const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS"
export const CREATE_COMPANY_CLEAR_SUCCESS = "CREATE_COMPANY_CLEAR_SUCCESS"
export const CREATE_COMPANY_FAIL = "CREATE_COMPANY_FAIL" 

export const UPDATE_COMPANY = "UPDATE_COMPANY"
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
export const UPDATE_COMPANY_CLEAR_SUCCESS = "UPDATE_COMPANY_CLEAR_SUCCESS"
export const UPDATE_COMPANY_FAIL = "UPDATE_COMPANY_FAIL" 

export const DELETE_COMPANY = "DELETE_COMPANY"
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
export const DELETE_COMPANY_CLEAR_SUCCESS = "DELETE_COMPANY_CLEAR_SUCCESS"
export const DELETE_COMPANY_FAIL = "DELETE_COMPANY_FAIL" 