export const GET_QUOTATION_CUSTOMER_ID = "GET_QUOTATION_CUSTOMER_ID"
export const GET_QUOTATION_CUSTOMER_ID_CLEAR = "GET_QUOTATION_CUSTOMER_ID_CLEAR"
export const GET_QUOTATION_CUSTOMER_ID_SUCCESS = "GET_QUOTATION_CUSTOMER_ID_SUCCESS"
export const GET_QUOTATION_CUSTOMER_ID_FAIL = "GET_QUOTATION_CUSTOMER_ID_FAIL"

export const GET_QUOTATION_PRODUCT_ID = "GET_QUOTATION_PRODUCT_ID"
export const GET_QUOTATION_PRODUCT_ID_CLEAR = "GET_QUOTATION_PRODUCT_ID_CLEAR"
export const GET_QUOTATION_PRODUCT_ID_SUCCESS = "GET_QUOTATION_PRODUCT_ID_SUCCESS"
export const GET_QUOTATION_PRODUCT_ID_FAIL = "GET_QUOTATION_PRODUCT_ID_FAIL"

export const GET_QUOTATION_PRODUCT_ADD = "GET_QUOTATION_PRODUCT_ADD"
export const GET_QUOTATION_PRODUCT_ADD_SUCCESS = "GET_QUOTATION_PRODUCT_ADD_SUCCESS"
export const GET_QUOTATION_PRODUCT_ADD_CLEAR = "GET_QUOTATION_PRODUCT_ADD_CLEAR"
export const GET_QUOTATION_PRODUCT_ADD_FAIL = "GET_QUOTATION_PRODUCT_ADD_FAIL"

export const POST_QUOTATION = "POST_QUOTATION"
export const POST_QUOTATION_SUCCESS = "POST_QUOTATION_SUCCESS"
export const POST_QUOTATION_CLEAR = "POST_QUOTATION_CLEAR"
export const POST_QUOTATION_FAIL = "POST_QUOTATION_FAIL"

export const GET_QUOTATION_ID = "GET_QUOTATION_ID"
export const GET_QUOTATION_ID_SUCCESS = "GET_QUOTATION_ID_SUCCESS"
export const GET_QUOTATION_ID_FAIL = "GET_QUOTATION_ID_FAIL"

export const GET_QUOTATION = "GET_QUOTATION"
export const GET_QUOTATION_SUCCESS = "GET_QUOTATION_SUCCESS"
export const GET_QUOTATION_FAIL = "GET_QUOTATION_FAIL" 