export const GET_QUOTATION_CUSTOMER_ID = "GET_QUOTATION_CUSTOMER_ID"
export const GET_QUOTATION_CUSTOMER_ID_CLEAR = "GET_QUOTATION_CUSTOMER_ID_CLEAR"
export const GET_QUOTATION_CUSTOMER_ID_SUCCESS = "GET_QUOTATION_CUSTOMER_ID_SUCCESS"
export const GET_QUOTATION_CUSTOMER_ID_FAIL = "GET_QUOTATION_CUSTOMER_ID_FAIL"

export const GET_QUOTATION_PRODUCT_ID = "GET_QUOTATION_PRODUCT_ID"
export const GET_QUOTATION_PRODUCT_ID_CLEAR = "GET_QUOTATION_PRODUCT_ID_CLEAR"
export const GET_QUOTATION_PRODUCT_ID_SUCCESS = "GET_QUOTATION_PRODUCT_ID_SUCCESS"
export const GET_QUOTATION_PRODUCT_ID_FAIL = "GET_QUOTATION_PRODUCT_ID_FAIL"